server:
  port: 8080

spring:
  application:
    name: event-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml
  task:
    scheduling:
      pool:
        size: 3

logging:
  level:
    root: INFO
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    url: /openapi.yaml

jwt:
  secret-key: 63bafba7ae994afe7dc2dc86d7fb65294963f3b834f65fc4df04f692092ec043
  lifetime: 86400000

admin:
  username: admin
  password: admin

task:
  fixed-delay-millis: 10000
